default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: rails-study-app_development

test:
  <<: *default
  database: rails-study-app_test
production:

  <<: *default
  database: rails-study-app_production
  username: rails-study-app
  password: <%= ENV['RAILS-STUDY-APP_DATABASE_PASSWORD'] %>
